"""empty message

Revision ID: e7eba262d455
Revises: 
Create Date: 2019-08-20 10:12:00.900075

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e7eba262d455'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people_ironTriangle', sa.Column('ironTriangle_code', sa.String(length=320), nullable=True))
    op.add_column('people_ironTriangle', sa.Column('people_code', sa.String(length=320), nullable=True))
    op.drop_constraint('people_ironTriangle_ibfk_1', 'people_ironTriangle', type_='foreignkey')
    op.drop_constraint('people_ironTriangle_ibfk_2', 'people_ironTriangle', type_='foreignkey')
    op.create_foreign_key(None, 'people_ironTriangle', 'ironTriangleInfo', ['ironTriangle_code'], ['iron_triangle_code'])
    op.create_foreign_key(None, 'people_ironTriangle', 'peopleInfo', ['people_code'], ['people_code'])
    op.drop_column('people_ironTriangle', 'people_id')
    op.drop_column('people_ironTriangle', 'ironTriangle_id')
    op.add_column('people_project', sa.Column('people_code', sa.String(length=320), nullable=True))
    op.add_column('people_project', sa.Column('project_code', sa.String(length=320), nullable=True))
    op.drop_constraint('people_project_ibfk_1', 'people_project', type_='foreignkey')
    op.drop_constraint('people_project_ibfk_2', 'people_project', type_='foreignkey')
    op.create_foreign_key(None, 'people_project', 'projectInfo', ['project_code'], ['project_code'])
    op.create_foreign_key(None, 'people_project', 'peopleInfo', ['people_code'], ['people_code'])
    op.drop_column('people_project', 'people_id')
    op.drop_column('people_project', 'project_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people_project', sa.Column('project_id', mysql.VARCHAR(length=320), nullable=True))
    op.add_column('people_project', sa.Column('people_id', mysql.VARCHAR(length=320), nullable=True))
    op.drop_constraint(None, 'people_project', type_='foreignkey')
    op.drop_constraint(None, 'people_project', type_='foreignkey')
    op.create_foreign_key('people_project_ibfk_2', 'people_project', 'projectInfo', ['project_id'], ['project_code'])
    op.create_foreign_key('people_project_ibfk_1', 'people_project', 'peopleInfo', ['people_id'], ['people_code'])
    op.drop_column('people_project', 'project_code')
    op.drop_column('people_project', 'people_code')
    op.add_column('people_ironTriangle', sa.Column('ironTriangle_id', mysql.VARCHAR(length=320), nullable=True))
    op.add_column('people_ironTriangle', sa.Column('people_id', mysql.VARCHAR(length=320), nullable=True))
    op.drop_constraint(None, 'people_ironTriangle', type_='foreignkey')
    op.drop_constraint(None, 'people_ironTriangle', type_='foreignkey')
    op.create_foreign_key('people_ironTriangle_ibfk_2', 'people_ironTriangle', 'ironTriangleInfo', ['ironTriangle_id'], ['iron_triangle_code'])
    op.create_foreign_key('people_ironTriangle_ibfk_1', 'people_ironTriangle', 'peopleInfo', ['people_id'], ['people_code'])
    op.drop_column('people_ironTriangle', 'people_code')
    op.drop_column('people_ironTriangle', 'ironTriangle_code')
    # ### end Alembic commands ###
