# 连接数据库设置
SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://root:$Mynew510$@localhost:3306/webData?charset=utf8'
SQLALCHEMY_TRACK_MODIFICATIONS = True
# flask设置
FLASK_SERVER_NAME = '0.0.0.0:8090'
FLASK_DEBUG = True
# flask-restplus设置
RESTPLUS_SWAGGER_UI_DOC_EXPANSION = 'list'
RESTPLUS_VALIDATE = True
RESTPLUS_MASK_SWAGGER = False
RESTPLUS_ERROR_404_HELP = False



